# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: windows-2022
  #name: 'my-self-hosted-pool'

strategy:
  matrix:
    chromeRun:
      browser: "chrome"
#    firefoxRun:
#      browser: "firefox"
#    edgeRun:
#      browser: "edge"
steps:
#- task: JavaToolInstaller@1
#  inputs:
#    versionSpec: '23'
#    jdkArchitectureOption: 'x64'
#    jdkSourceOption: 'PreInstalled'
#- task: Docker@2 # install Docker
#- task: DockerInstaller@0
#  displayName: Docker Installer
#  inputs:
#    dockerVersion: 27.5.0
#    releaseType: stable

- script: docker run -d --name browser-container -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-$(browser):latest
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'clean test'
  env:
    TEST_BROWSER: $(browser)
  continueOnError: true
- script: docker stop browser-container & docker rm browser-container

